on:
  push:
    branches:
      - master

name: "Proselint"

jobs:
  proselint:
    name: Proselint
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run proselint
        uses: ./
